49  recieved from forex screener
2020-09-26 01:05:52.978386  script ran
49  recieved from forex screener
2020-09-26 01:10:40.263991  script ran
49  recieved from forex screener
2020-09-26 01:16:10.127633  script ran
49  recieved from forex screener
2020-09-26 01:20:40.271246  script ran
49  recieved from forex screener
2020-09-26 01:25:46.098102  script ran
49  recieved from forex screener
2020-09-26 01:30:49.010418  script ran
49  recieved from forex screener
2020-09-26 01:35:34.290723  script ran
49  recieved from forex screener
2020-09-26 01:40:39.094712  script ran
49  recieved from forex screener
2020-09-26 01:45:41.254651  script ran
49  recieved from forex screener
2020-09-26 01:50:56.556651  script ran
49  recieved from forex screener
2020-09-26 01:55:52.334427  script ran
49  recieved from forex screener
2020-09-26 02:01:07.007337  script ran
Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

49  recieved from forex screener
2020-09-26 02:16:08.633467  script ran
Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

49  recieved from forex screener
2020-09-26 02:26:14.269623  script ran
Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

49  recieved from forex screener
2020-09-26 02:40:55.441411  script ran
49  recieved from forex screener
2020-09-26 02:46:07.525873  script ran
Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.446
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.439
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.743
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.325
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.012
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.543
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.234
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.286
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.349
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.918
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.530
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.616
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.328
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.152
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.047
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.090
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.879
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.287
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.082
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.487
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.915
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.194
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.606
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.124
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.097
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.722
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.172
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.709
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.741
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.156
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.250
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.025
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 288.790
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.719
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.081
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.344
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 234.303
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 257.568
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.637
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.214
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.564
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.258
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.040
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.414
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.601
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.598
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.081
  (Session info: headless chrome=83.0.4103.97)

0  recieved from forex screener
49  recieved from forex screener
2020-09-26 09:49:28.057187  script ran
49  recieved from forex screener
2020-09-26 09:50:21.366017  script ran
49  recieved from forex screener
2020-09-26 09:55:24.523004  script ran
49  recieved from forex screener
2020-09-26 10:00:25.526442  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 10:05:32.137939  script ran
49  recieved from forex screener
2020-09-26 10:10:25.619647  script ran
49  recieved from forex screener
2020-09-26 10:15:26.344329  script ran
49  recieved from forex screener
2020-09-26 10:20:25.011706  script ran
49  recieved from forex screener
2020-09-26 10:25:26.375570  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 10:30:32.784371  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 10:35:31.375039  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 10:40:31.454126  script ran
49  recieved from forex screener
2020-09-26 10:45:25.666805  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 10:50:32.917273  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 10:55:31.565033  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 11:00:34.413649  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 11:05:32.418746  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 11:10:30.065291  script ran
49  recieved from forex screener
2020-09-26 11:15:26.116365  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 11:20:33.482753  script ran
49  recieved from forex screener
2020-09-26 11:25:25.995298  script ran
49  recieved from forex screener
2020-09-26 11:30:25.343021  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 11:35:29.341966  script ran
49  recieved from forex screener
2020-09-26 11:40:25.088345  script ran
49  recieved from forex screener
2020-09-26 11:45:24.037593  script ran
49  recieved from forex screener
2020-09-26 11:50:25.116134  script ran
49  recieved from forex screener
2020-09-26 11:55:24.056909  script ran
49  recieved from forex screener
2020-09-26 12:00:28.616560  script ran
49  recieved from forex screener
2020-09-26 12:05:25.621818  script ran
49  recieved from forex screener
2020-09-26 12:10:27.060724  script ran
49  recieved from forex screener
2020-09-26 12:15:26.789531  script ran
49  recieved from forex screener
2020-09-26 12:20:26.154640  script ran
49  recieved from forex screener
2020-09-26 12:25:26.594723  script ran
49  recieved from forex screener
2020-09-26 12:30:27.365598  script ran
49  recieved from forex screener
2020-09-26 12:35:25.620305  script ran
49  recieved from forex screener
2020-09-26 12:40:26.345838  script ran
49  recieved from forex screener
2020-09-26 12:45:24.384952  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-26 12:50:33.355021  script ran
49  recieved from forex screener
2020-09-26 12:55:27.274279  script ran
49  recieved from forex screener
2020-09-26 13:00:27.469410  script ran
49  recieved from forex screener
2020-09-26 13:05:29.280251  script ran
49  recieved from forex screener
2020-09-26 13:10:26.009454  script ran
49  recieved from forex screener
2020-09-26 13:15:26.393810  script ran
49  recieved from forex screener
2020-09-26 13:20:26.026518  script ran
49  recieved from forex screener
2020-09-26 13:25:26.391914  script ran
